### ISSUE TITLE
 Could not find a suitable TLS CA certificate bundle, invalid path: /home/mitmproxyuser/.mitmproxy/mitmproxy-ca-cert.pem

### ISSUE THREAD

**Issue by JarLob** [GitHubSecurityLab/actions-permissions#14]
https://github.com/tspascoal-demo2/MyShuttle/actions/runs/5443639260/jobs/9900419190

**Comment by roman-parkhunovskyi** [comment]
Same thing, a lot of issues related to certificates, both with java build and k8s manipulations. As soon as I remove `GitHubSecurityLab/actions-permissions/monitor` action, everything works again.
Another side effect, `actions/checkout@v3` takes 15min to checkout the repository.
Not that critical to have this `GitHubSecurityLab/actions-permissions/monitor` action, removing it for good as it is not GA at all.

**Comment by JarLob** [comment]
Should be fixed with hosts filtering. Please try f62d32cd684392a758c627a58e0756b734bd54fd and reopen if still present.
