### ISSUE TITLE
bug: self signed certificate error

### ISSUE THREAD

**Issue by electriquo** [GitHubSecurityLab/actions-permissions#20]
adding `uses: GitHubSecurityLab/actions-permissions/monitor@v1` as the first jobs steps causes

> docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority.

**Comment by JarLob** [comment]
Should be fixed with f62d32cd684392a758c627a58e0756b734bd54fd Please reopen if still present.
