### ISSUE TITLE
Assumes runner can sudo to root?

### ISSUE THREAD

**Issue by brianjmurrell** [GitHubSecurityLab/actions-permissions#26]
It would seem that this all requires that a workflow is able to `sudo` to root(!) on a runner, yes?

So if one was building ([more] secure) self-hosted runners without that capability for an action to gain root on one's runner, this action not work, yes?

Further, it assumes that a Linux runner is running on Ubuntu also.

**Comment by JarLob** [comment]
Yes, the monitor needs privileges to modify system files for traffic interception.
The action supports the standard runners provided by GitHub, but you are welcome to create a pull request that adds support for other operating systems.
