### ISSUE TITLE
GitHub Enterprise Support

### ISSUE THREAD

**Issue by martincostello** [GitHubSecurityLab/actions-permissions#8]
I was taking a look at the actions with a view to maybe trying them out in GitHub Enterprise Server, but it _seems_ that the actions assume running in github.com in a few places ([example](https://github.com/search?q=repo%3AGitHubSecurityLab%2Factions-permissions%20%22api.github.com%22&type=code)).

If the `GITHUB_API_URL`, `GITHUB_GRAPHQL_URL` and `GITHUB_SERVER_URL` environment variables were inspected when building up the list of hosts/URLs to inspect requests to then I would have thought it would then theoretically work.

**Comment by JarLob** [comment]
Good point, thank you for you feedback! If you could try applying the changes and try it with GHE (you can use `- uses: martincostello/actions-permissionsmonitor@your_branch`) I would merge that!

**Comment by martincostello** [comment]
Sure - I'll try it out later this week and see what happens!

**Comment by vedevilolivedev** [comment]
I went through and replaced api.github.com with our domain/api/v3, and all other github.com to our domain and so far it's seeming to work just fine. Not sure how to automate this though

**Comment by JarLob** [comment]
Implemented in f62d32cd684392a758c627a58e0756b734bd54fd
